// Code generated by MockGen. DO NOT EDIT.
// Source: internal/agent/memory/memory.go
//
// Generated by this command:
//
//	mockgen -source=internal/agent/memory/memory.go -destination=internal/agent/memory/mocks/mock_memory.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	agent "github.com/SamyRai/juleson/internal/agent"
	gomock "go.uber.org/mock/gomock"
)

// MockMemory is a mock of Memory interface.
type MockMemory struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryMockRecorder
	isgomock struct{}
}

// MockMemoryMockRecorder is the mock recorder for MockMemory.
type MockMemoryMockRecorder struct {
	mock *MockMemory
}

// NewMockMemory creates a new mock instance.
func NewMockMemory(ctrl *gomock.Controller) *MockMemory {
	mock := &MockMemory{ctrl: ctrl}
	mock.recorder = &MockMemoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemory) EXPECT() *MockMemoryMockRecorder {
	return m.recorder
}

// GetDecisionHistory mocks base method.
func (m *MockMemory) GetDecisionHistory(ctx context.Context, limit int) ([]agent.Decision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDecisionHistory", ctx, limit)
	ret0, _ := ret[0].([]agent.Decision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDecisionHistory indicates an expected call of GetDecisionHistory.
func (mr *MockMemoryMockRecorder) GetDecisionHistory(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDecisionHistory", reflect.TypeOf((*MockMemory)(nil).GetDecisionHistory), ctx, limit)
}

// Recall mocks base method.
func (m *MockMemory) Recall(ctx context.Context, pattern string) ([]agent.Learning, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recall", ctx, pattern)
	ret0, _ := ret[0].([]agent.Learning)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recall indicates an expected call of Recall.
func (mr *MockMemoryMockRecorder) Recall(ctx, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recall", reflect.TypeOf((*MockMemory)(nil).Recall), ctx, pattern)
}

// RecordDecision mocks base method.
func (m *MockMemory) RecordDecision(ctx context.Context, decision agent.Decision) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordDecision", ctx, decision)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordDecision indicates an expected call of RecordDecision.
func (mr *MockMemoryMockRecorder) RecordDecision(ctx, decision any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordDecision", reflect.TypeOf((*MockMemory)(nil).RecordDecision), ctx, decision)
}

// Store mocks base method.
func (m *MockMemory) Store(ctx context.Context, learning agent.Learning) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, learning)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockMemoryMockRecorder) Store(ctx, learning any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockMemory)(nil).Store), ctx, learning)
}

// UpdateLearningConfidence mocks base method.
func (m *MockMemory) UpdateLearningConfidence(ctx context.Context, learningID string, successful bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLearningConfidence", ctx, learningID, successful)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLearningConfidence indicates an expected call of UpdateLearningConfidence.
func (mr *MockMemoryMockRecorder) UpdateLearningConfidence(ctx, learningID, successful any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLearningConfidence", reflect.TypeOf((*MockMemory)(nil).UpdateLearningConfidence), ctx, learningID, successful)
}
