// Code generated by MockGen. DO NOT EDIT.
// Source: internal/agent/review/reviewer.go
//
// Generated by this command:
//
//	mockgen -source=internal/agent/review/reviewer.go -destination=internal/agent/review/mocks/mock_reviewer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	agent "github.com/SamyRai/juleson/internal/agent"
	gomock "go.uber.org/mock/gomock"
)

// MockReviewer is a mock of Reviewer interface.
type MockReviewer struct {
	ctrl     *gomock.Controller
	recorder *MockReviewerMockRecorder
	isgomock struct{}
}

// MockReviewerMockRecorder is the mock recorder for MockReviewer.
type MockReviewerMockRecorder struct {
	mock *MockReviewer
}

// NewMockReviewer creates a new mock instance.
func NewMockReviewer(ctrl *gomock.Controller) *MockReviewer {
	mock := &MockReviewer{ctrl: ctrl}
	mock.recorder = &MockReviewerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewer) EXPECT() *MockReviewerMockRecorder {
	return m.recorder
}

// Review mocks base method.
func (m *MockReviewer) Review(ctx context.Context, changes []agent.Change) (*agent.ReviewResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Review", ctx, changes)
	ret0, _ := ret[0].(*agent.ReviewResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Review indicates an expected call of Review.
func (mr *MockReviewerMockRecorder) Review(ctx, changes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Review", reflect.TypeOf((*MockReviewer)(nil).Review), ctx, changes)
}
