package agent

import (
	"context"
	"time"
)

// AgentState represents the current state of the agent
type AgentState string

const (
	StateIdle       AgentState = "IDLE"
	StateAnalyzing  AgentState = "ANALYZING"
	StatePlanning   AgentState = "PLANNING"
	StateExecuting  AgentState = "EXECUTING"
	StateReviewing  AgentState = "REVIEWING"
	StateReflecting AgentState = "REFLECTING"
	StateComplete   AgentState = "COMPLETE"
	StateFailed     AgentState = "FAILED"
	StateError      AgentState = "ERROR"
)

// Goal represents what the agent should achieve
type Goal struct {
	ID          string
	Description string
	Constraints []string
	Context     GoalContext
	Priority    Priority
	Deadline    *time.Time
}

// GoalContext provides context for achieving the goal
type GoalContext struct {
	ProjectPath   string
	SourceID      string
	Repository    string
	Branch        string
	RelatedIssues []string
	RelatedPRs    []string
}

// Priority levels for goals and tasks
type Priority string

const (
	PriorityCritical Priority = "CRITICAL"
	PriorityHigh     Priority = "HIGH"
	PriorityMedium   Priority = "MEDIUM"
	PriorityLow      Priority = "LOW"
)

// Result represents the outcome of agent execution
type Result struct {
	Goal      Goal
	Success   bool
	State     AgentState
	Tasks     []TaskResult
	Artifacts []Artifact
	PRs       []string
	Issues    []string
	Duration  time.Duration
	Error     error
	Summary   string
	Learnings []Learning
}

// TaskResult represents the outcome of a single task
type TaskResult struct {
	TaskID       string
	Name         string
	Success      bool
	Duration     time.Duration
	Tool         string
	Changes      []Change
	TestResults  *TestResults
	ReviewResult *ReviewResult
	Error        error
}

// Change represents a code change
type Change struct {
	FilePath    string
	Type        ChangeType
	Additions   int
	Deletions   int
	Patch       string
	Description string
}

// ChangeType categorizes the type of change
type ChangeType string

const (
	ChangeTypeAdd    ChangeType = "ADD"
	ChangeTypeModify ChangeType = "MODIFY"
	ChangeTypeDelete ChangeType = "DELETE"
	ChangeTypeRename ChangeType = "RENAME"
)

// Artifact represents output generated by the agent
type Artifact struct {
	Type        ArtifactType
	Path        string
	Content     string
	Description string
	Metadata    map[string]interface{}
}

// ArtifactType categorizes artifacts
type ArtifactType string

const (
	ArtifactTypeCode          ArtifactType = "CODE"
	ArtifactTypeTest          ArtifactType = "TEST"
	ArtifactTypeDocumentation ArtifactType = "DOCUMENTATION"
	ArtifactTypeConfiguration ArtifactType = "CONFIGURATION"
	ArtifactTypeReport        ArtifactType = "REPORT"
)

// Decision represents a decision made by the agent
type Decision struct {
	ID           string
	Timestamp    time.Time
	State        AgentState
	Type         DecisionType
	Reasoning    string
	Action       string
	Confidence   float64
	Alternatives []string
	Outcome      *DecisionOutcome
}

// DecisionType categorizes agent decisions
type DecisionType string

const (
	DecisionTypeSelectTool    DecisionType = "SELECT_TOOL"
	DecisionTypeApprove       DecisionType = "APPROVE"
	DecisionTypeReject        DecisionType = "REJECT"
	DecisionTypeRequestChange DecisionType = "REQUEST_CHANGE"
	DecisionTypeAdaptPlan     DecisionType = "ADAPT_PLAN"
	DecisionTypeComplete      DecisionType = "COMPLETE"
	DecisionTypeRetry         DecisionType = "RETRY"
	DecisionTypeAbort         DecisionType = "ABORT"
)

// DecisionOutcome records what happened after a decision
type DecisionOutcome struct {
	Success   bool
	Duration  time.Duration
	Result    interface{}
	Error     error
	Learnings []string
}

// Feedback represents feedback provided to or by the agent
type Feedback struct {
	ID         string
	Timestamp  time.Time
	Source     string // "human", "test", "review", etc.
	Type       FeedbackType
	Severity   Severity
	Subject    string // What the feedback is about
	Message    string
	Suggestion string
	Location   *Location
}

// FeedbackType categorizes feedback
type FeedbackType string

const (
	FeedbackTypePositive   FeedbackType = "POSITIVE"
	FeedbackTypeCorrection FeedbackType = "CORRECTION"
	FeedbackTypeSuggestion FeedbackType = "SUGGESTION"
	FeedbackTypeQuestion   FeedbackType = "QUESTION"
	FeedbackTypeWarning    FeedbackType = "WARNING"
)

// Severity levels for feedback and issues
type Severity string

const (
	SeverityCritical Severity = "CRITICAL"
	SeverityHigh     Severity = "HIGH"
	SeverityMedium   Severity = "MEDIUM"
	SeverityLow      Severity = "LOW"
	SeverityInfo     Severity = "INFO"
)

// Location points to a specific place in code
type Location struct {
	FilePath  string
	Line      int
	Column    int
	EndLine   int
	EndColumn int
}

// Learning represents knowledge gained from experience
type Learning struct {
	ID           string
	Timestamp    time.Time
	Context      string
	Pattern      string
	Lesson       string
	Confidence   float64
	Applications int // How many times successfully applied
}

// TestResults represents test execution results
type TestResults struct {
	Passed   int
	Failed   int
	Skipped  int
	Duration time.Duration
	Coverage float64
	Failures []TestFailure
}

// TestFailure represents a failed test
type TestFailure struct {
	TestName string
	Message  string
	Stack    string
	Location *Location
}

// ReviewResult represents code review outcome
type ReviewResult struct {
	Decision         ReviewDecision
	Comments         []ReviewComment
	Score            float64 // 0-100
	Summary          string
	Approved         bool
	ChangesRequested bool
}

// ReviewDecision categorizes review outcomes
type ReviewDecision string

const (
	ReviewDecisionApprove        ReviewDecision = "APPROVE"
	ReviewDecisionRequestChanges ReviewDecision = "REQUEST_CHANGES"
	ReviewDecisionComment        ReviewDecision = "COMMENT"
	ReviewDecisionReject         ReviewDecision = "REJECT"
)

// ReviewComment represents a code review comment
type ReviewComment struct {
	ID         string
	Location   *Location
	Severity   Severity
	Category   ReviewCategory
	Message    string
	Suggestion string
	Example    string
}

// ReviewCategory categorizes review comments
type ReviewCategory string

const (
	ReviewCategoryCorrectness   ReviewCategory = "CORRECTNESS"
	ReviewCategorySecurity      ReviewCategory = "SECURITY"
	ReviewCategoryPerformance   ReviewCategory = "PERFORMANCE"
	ReviewCategoryStyle         ReviewCategory = "STYLE"
	ReviewCategoryBestPractice  ReviewCategory = "BEST_PRACTICE"
	ReviewCategoryArchitecture  ReviewCategory = "ARCHITECTURE"
	ReviewCategoryDocumentation ReviewCategory = "DOCUMENTATION"
	ReviewCategoryTesting       ReviewCategory = "TESTING"
)

// Agent is the main interface for the AI agent
type Agent interface {
	// Execute a goal
	Execute(ctx context.Context, goal Goal) (*Result, error)

	// Get current state
	GetState() AgentState

	// Get execution history
	GetHistory() []Decision

	// Pause execution
	Pause() error

	// Resume execution
	Resume() error

	// Stop execution
	Stop() error

	// Provide feedback
	ProvideFeedback(feedback Feedback) error

	// Get current progress
	GetProgress() *Progress
}

// Progress represents current execution progress
type Progress struct {
	State          AgentState
	CurrentTask    string
	CompletedTasks int
	TotalTasks     int
	Progress       float64 // 0-100
	Message        string
	NextSteps      []string
	Timestamp      time.Time
}

// Task represents work to be done by the agent
type Task struct {
	ID           string
	Name         string
	Description  string
	Prompt       string
	Priority     Priority
	Dependencies []string
	Tool         string // Preferred tool name
	Context      map[string]interface{}
	State        TaskState
	Result       *TaskResult
}

// TaskState represents the state of a task
type TaskState string

const (
	TaskStatePending    TaskState = "PENDING"
	TaskStateInProgress TaskState = "IN_PROGRESS"
	TaskStateReviewing  TaskState = "REVIEWING"
	TaskStateComplete   TaskState = "COMPLETE"
	TaskStateFailed     TaskState = "FAILED"
	TaskStateSkipped    TaskState = "SKIPPED"
)

// Reasoning represents the agent's chain-of-thought reasoning
type Reasoning struct {
	ChainOfThought []string  `json:"chain_of_thought"`
	Confidence     float64   `json:"confidence"`
	Alternatives   []string  `json:"alternatives"`
	SelectedPath   string    `json:"selected_path"`
	Timestamp      time.Time `json:"timestamp"`
}

// Observation represents what the agent observes from the environment
type Observation struct {
	Type        ObservationType        `json:"type"`
	Source      string                 `json:"source"`
	Content     string                 `json:"content"`
	Metadata    map[string]interface{} `json:"metadata"`
	Timestamp   time.Time              `json:"timestamp"`
	Reliability float64                `json:"reliability"` // 0.0-1.0
}

// ObservationType categorizes observations
type ObservationType string

const (
	ObservationTypeCode        ObservationType = "CODE"
	ObservationTypeTest        ObservationType = "TEST"
	ObservationTypeError       ObservationType = "ERROR"
	ObservationTypeMetric      ObservationType = "METRIC"
	ObservationTypeFeedback    ObservationType = "FEEDBACK"
	ObservationTypeEnvironment ObservationType = "ENVIRONMENT"
)

// Action represents an action the agent can take
type Action struct {
	Type       ActionType             `json:"type"`
	Tool       string                 `json:"tool"`
	Parameters map[string]interface{} `json:"parameters"`
	Reasoning  string                 `json:"reasoning"`
	Expected   string                 `json:"expected_outcome"`
	Timestamp  time.Time              `json:"timestamp"`
}

// ActionType categorizes actions
type ActionType string

const (
	ActionTypeExecute  ActionType = "EXECUTE"
	ActionTypeQuery    ActionType = "QUERY"
	ActionTypeModify   ActionType = "MODIFY"
	ActionTypeCreate   ActionType = "CREATE"
	ActionTypeDelete   ActionType = "DELETE"
	ActionTypeValidate ActionType = "VALIDATE"
	ActionTypeWait     ActionType = "WAIT"
)

// Constraint represents a limitation on agent actions
type Constraint struct {
	Type        string
	Description string
	Validator   func(action Action) error
}
