// Code generated by MockGen. DO NOT EDIT.
// Source: internal/llm/provider.go
//
// Generated by this command:
//
//	mockgen -source=internal/llm/provider.go -destination=internal/llm/mocks/mock_provider.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	llm "github.com/SamyRai/juleson/internal/llm"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// GenerateContent mocks base method.
func (m *MockProvider) GenerateContent(ctx context.Context, req llm.Request) (*llm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateContent", ctx, req)
	ret0, _ := ret[0].(*llm.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateContent indicates an expected call of GenerateContent.
func (mr *MockProviderMockRecorder) GenerateContent(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateContent", reflect.TypeOf((*MockProvider)(nil).GenerateContent), ctx, req)
}

// GenerateContentStream mocks base method.
func (m *MockProvider) GenerateContentStream(ctx context.Context, req llm.Request) (<-chan llm.StreamChunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateContentStream", ctx, req)
	ret0, _ := ret[0].(<-chan llm.StreamChunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateContentStream indicates an expected call of GenerateContentStream.
func (mr *MockProviderMockRecorder) GenerateContentStream(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateContentStream", reflect.TypeOf((*MockProvider)(nil).GenerateContentStream), ctx, req)
}
